-- Script de Inicialización de Base de Datos (Full Schema)

-- 1. Tabla de Configuración de Fuentes (etl_sources)
-- Esta tabla define qué fuentes se deben monitorear y cómo.
CREATE TABLE IF NOT EXISTS public.etl_sources (
  id text not null,
  name text not null,
  active boolean not null default false,
  type text null, -- Ej: 'api', 'scrape', 'complex_scraper'
  schedule_cron text not null, -- Ej: '*/5 * * * *'
  config jsonb null default '{}'::jsonb, -- Ej: { "url": "...", "headers": {...} }
  storage_config jsonb null default '{}'::jsonb, -- Ej: { "path": "raw/gas" }
  created_at timestamp with time zone null default timezone ('utc'::text, now()),
  updated_at timestamp with time zone null default timezone ('utc'::text, now()),
  constraint etl_sources_pkey primary key (id)
) TABLESPACE pg_default;

COMMENT ON TABLE public.etl_sources IS 'Configuración maestra de las fuentes de datos para el ETL';

-- 2. Tipos ENUM para el historial
-- Usamos bloques DO para evitar errores si los tipos ya existen
DO $$ BEGIN
    CREATE TYPE source_update_method AS ENUM ('api', 'scraping', 'html', 'archivo', 'complex_scraper');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE source_check_status AS ENUM ('no_change', 'changed', 'failed');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 3. Tabla de Historial de Ejecuciones (source_check_history)
-- Registra cada vez que el scheduler verifica una fuente.
CREATE TABLE IF NOT EXISTS public.source_check_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id TEXT NOT NULL REFERENCES public.etl_sources(id) ON DELETE CASCADE,
    status source_check_status NOT NULL,
    checksum TEXT, -- Hash MD5 del contenido para detectar cambios
    metadata JSONB DEFAULT '{}'::jsonb, -- Almacena url, method, notes, error details
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Índices para optimización
-- Permite obtener rápidamente el último estado: ORDER BY created_at DESC LIMIT 1
CREATE INDEX IF NOT EXISTS idx_history_source_latest ON public.source_check_history (source_id, created_at DESC);
-- Permite filtrar por estado (ej: ver todos los fallos recientes)
CREATE INDEX IF NOT EXISTS idx_history_status ON public.source_check_history (status, created_at DESC);

COMMENT ON TABLE public.source_check_history IS 'Log inmutable de verificaciones de fuentes (Check Updates)';
